USE [SHC]
GO

/****** Object:  Table [dbo].[Country]    Script Date: 25/05/2017 4:00:23 p.m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Country](
	[idCou] [int] IDENTITY(1,1) NOT NULL,
	[CouName] [varchar](128) NOT NULL,
	[CouCode] [varchar](12) NOT NULL,
 CONSTRAINT [PK_Country] PRIMARY KEY CLUSTERED 
(
	[idCou] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

